global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using SequentialGuid;
global using UploadFileCustomExtensions.Entities;
global using UploadFileCustomExtensions.Models.Record;
global using UploadFileCustomExtensions.Models.Request;
global using UploadFileCustomExtensions.StorageProviders;
